Profession.destroy_all
print "Seeding database..."

professions = [
  { title: 'doctor', salary: 13200, expenses: [ { name: "Taxes", amount: 3420 }, { name: "Mortgage Payment", amount: 1900 }, { name: "School Loan Payment", amount: 750 }, { name: "Car Payment", amount: 380 }, { name: "Credit Card Payment", amount: 270 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 2880 } ], childCost: 640, debts: [ { name: "Mortgage", amount: 202000 }, { name: "School Loans", amount: 150000 }, { name: "Car", amount: 19000 }, { name: "Credit Card", amount: 9000 }, { name: "Retail", amount: 1000 }], savings: 400 },
  { title: 'nurse', salary: 3100, expenses: [ { name: "Taxes", amount: 600 }, { name: "Mortgage Payment", amount: 400 }, { name: "School Loan Payment", amount: 30 }, { name: "Car Payment", amount: 100 }, { name: "Credit Card Payment", amount: 90 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 710 } ], childCost: 170, debts: [ { name: "Mortgage", amount: 47000 }, { name: "School Loans", amount: 6000 }, { name: "Car", amount: 5000 }, { name: "Credit Card", amount: 3000 }, { name: "Retail", amount: 1000 }], savings: 480 },
  { title: 'mechanic', salary: 2000, expenses: [ { name: "Taxes", amount: 360 }, { name: "Mortgage Payment", amount: 300 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 60 }, { name: "Credit Card Payment", amount: 60 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 450 } ], childCost: 110, debts: [ { name: "Mortgage", amount: 31000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 3000 }, { name: "Credit Card", amount: 2000 }, { name: "Retail", amount: 1000 }], savings: 670 },
  { title: 'truck driver', salary: 2500, expenses: [ { name: "Taxes", amount: 460 }, { name: "Mortgage Payment", amount: 400 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 80 }, { name: "Credit Card Payment", amount: 60 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 570 } ], childCost: 140, debts: [ { name: "Mortgage", amount: 38000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 4000 }, { name: "Credit Card", amount: 2000 }, { name: "Retail", amount: 1000 }], savings: 750 },
  { title: 'teacher', salary: 3300, expenses: [ { name: "Taxes", amount: 630 }, { name: "Mortgage Payment", amount: 500 }, { name: "School Loan Payment", amount: 60 }, { name: "Car Payment", amount: 100 }, { name: "Credit Card Payment", amount: 90 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 760 } ], childCost: 180, debts: [ { name: "Mortgage", amount: 50000 }, { name: "School Loans", amount: 12000 }, { name: "Car", amount: 5000 }, { name: "Credit Card", amount: 3000 }, { name: "Retail", amount: 1000 }], savings: 400 },
  { title: 'pilot', salary: 9500, expenses: [ { name: "Taxes", amount: 2350 }, { name: "Mortgage Payment", amount: 1330 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 300 }, { name: "Credit Card Payment", amount: 660 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 2210 } ], childCost: 480, debts: [ { name: "Mortgage", amount: 143000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 15000 }, { name: "Credit Card", amount: 22000 }, { name: "Retail", amount: 1000 }], savings: 400 },
  { title: 'business manager', salary: 4600, expenses: [ { name: "Taxes", amount: 910 }, { name: "Mortgage Payment", amount: 700 }, { name: "School Loan Payment", amount: 60 }, { name: "Car Payment", amount: 120 }, { name: "Credit Card Payment", amount: 90 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 1000 } ], childCost: 480, debts: [ { name: "Mortgage", amount: 75000 }, { name: "School Loans", amount: 12000 }, { name: "Car", amount: 6000 }, { name: "Credit Card", amount: 3000 }, { name: "Retail", amount: 1000 }], savings: 400 },
  { title: 'lawyer', salary: 7500, expenses: [ { name: "Taxes", amount: 1830 }, { name: "Mortgage Payment", amount: 1100 }, { name: "School Loan Payment", amount: 390 }, { name: "Car Payment", amount: 220 }, { name: "Credit Card Payment", amount: 180 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 1650 } ], childCost: 380, debts: [ { name: "Mortgage", amount: 115000 }, { name: "School Loans", amount: 78000 }, { name: "Car", amount: 11000 }, { name: "Credit Card", amount: 6000 }, { name: "Retail", amount: 1000 }], savings: 400 },
  { title: 'janitor', salary: 1600, expenses: [ { name: "Taxes", amount: 280 }, { name: "Mortgage Payment", amount: 200 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 60 }, { name: "Credit Card Payment", amount: 60 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 300 } ], childCost: 70, debts: [ { name: "Mortgage", amount: 20000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 4000 }, { name: "Credit Card", amount: 2000 }, { name: "Retail", amount: 1000 }], savings: 560 },
  { title: 'secretary', salary: 2500, expenses: [ { name: "Taxes", amount: 460 }, { name: "Mortgage Payment", amount: 400 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 80 }, { name: "Credit Card Payment", amount: 60 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 570 } ], childCost: 140, debts: [ { name: "Mortgage", amount: 38000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 4000 }, { name: "Credit Card", amount: 2000 }, { name: "Retail", amount: 1000 }], savings: 710 },
  { title: 'police officer', salary: 3000, expenses: [ { name: "Taxes", amount: 580 }, { name: "Mortgage Payment", amount: 400 }, { name: "School Loan Payment", amount: 0 }, { name: "Car Payment", amount: 100 }, { name: "Credit Card Payment", amount: 60 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 690 } ], childCost: 160, debts: [ { name: "Mortgage", amount: 46000 }, { name: "School Loans", amount: 0 }, { name: "Car", amount: 5000 }, { name: "Credit Card", amount: 2000 }, { name: "Retail", amount: 1000 }], savings: 520 },
  { title: 'engineer', salary: 4900, expenses: [ { name: "Taxes", amount: 1050 }, { name: "Mortgage Payment", amount: 700 }, { name: "School Loan Payment", amount: 60 }, { name: "Car Payment", amount: 140 }, { name: "Credit Card Payment", amount: 120 }, { name: "Retail Payment", amount: 50 }, { name: "Other", amount: 1090 } ], childCost: 250, debts: [ { name: "Mortgage", amount: 75000 }, { name: "School Loans", amount: 12000 }, { name: "Car", amount: 7000 }, { name: "Credit Card", amount: 4000 }, { name: "Retail", amount: 1000 }], savings: 400 }
]

success_count = 0
fail_count = 0

professions.each do |p|
  model = Profession.new(title: p[:title], salary: p[:salary], expenses: p[:expenses], childCost: p[:childCost], debts: p[:debts], savings: p[:savings] )
  model.save ? success_count += 1 : fail_count += 1
end

puts "done! \nProfession creations: #{success_count} successful, #{fail_count} failed."